# Generated by Django 5.2.15 on 2026-06-16 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_id', models.CharField(max_length=50, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('relationship_label', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='guardians/photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guardian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['guardian_id'],
            },
        ),
        migrations.CreateModel(
            name='GuardianContactPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_push', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_preference', to='guardians.guardian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('can_pickup', models.BooleanField(default=False)),
                ('receives_sms', models.BooleanField(default=True)),
                ('receives_email', models.BooleanField(default=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='guardians.guardian')),
            ],
            options={
                'ordering': ['-is_primary', 'relationship'],
            },
        ),
    ]
