# Generated by Django 5.2.15 on 2026-06-16 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HifzDailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('sabak', models.CharField(blank=True, max_length=150)),
                ('sabki', models.CharField(blank=True, max_length=150)),
                ('amukhta', models.CharField(blank=True, max_length=150)),
                ('juz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mistakes_count', models.PositiveIntegerField(default=0)),
                ('tajweed_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_progress', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_progress', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HifzEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_enrollment', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_enrollments', to='teachers.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HifzMistake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mistake_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('correction', models.TextField(blank=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='hifz.hifzdailyprogress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HifzMonthlyTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_pages', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_tajweed_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_mistakes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.branch')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='common.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_monthly_tracking', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_monthly_tracking', to='teachers.teacher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hifzdailyprogress',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_hifz_daily_progress'),
        ),
        migrations.AddConstraint(
            model_name='hifzmonthlytracking',
            constraint=models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_hifz_monthly_tracking'),
        ),
    ]
